name: docker_build

env:
   NAME: "klibio/example.bnd.rcp:"

on:
  workflow_dispatch:
  push:
    branches:
     - 'add_test_script'
  pull_request:
    branches:
     - 'main'

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       with:
        fetch-depth: 1
     - 
      name: Build docker image and push to docker hub
      id: script
      run: |
        /bin/bash ${GITHUB_WORKSPACE}/start.sh
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
