name: docker_build

on:
  push:
    branches:
     - 'gradle_build'
  pull_request:
    branches:
     - 'main'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
     - 
       name: Get current date
       id: date
       run: echo "::set-output name=date::$(date +'%Y.%m.%d-%H:%M:%S')"
     - 
       name: Set up QEMU
       uses: docker/setup-qemu-action@v1
     -
       name: Setup Docker Buildx
       uses: docker/setup-buildx-action@v1
     -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: klibio/example.bnd.rcp:${{ steps.date.outputs.date }}
     -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
